[package]
name = "convex-hull-pf"
version = "0.1.0"
authors = ["Lucille Blumire <llblumire@gmail.com>"]

[dependencies]
clap = "*"
image = "*"
ncollide = "*"
serde = "*"
serde_derive = "*"
toml = "*"
nalgebra = "*"