[start]
x = 40
y = 280

[end]
x = 780
y = 218

[[route]]
x = 390
y = 260

[[polygon]]
    [[polygon.point]]
    x = 150
    y = 350
    [[polygon.point]]
    x = 250
    y = 350
    [[polygon.point]]
    x = 250
    y = 300
    [[polygon.point]]
    x = 300
    y = 320
    [[polygon.point]]
    x = 300
    y = 230
    [[polygon.point]]
    x = 240
    y = 190
    [[polygon.point]]
    x = 175
    y = 190
    [[polygon.point]]
    x = 175
    y = 230
    [[polygon.point]]
    x = 90
    y = 300
    [[polygon.point]]
    x = 200
    y = 320

[[polygon]]
    [[polygon.point]]
    x = 525
    y = 365
    [[polygon.point]]
    x = 625
    y = 365
    [[polygon.point]]
    x = 625
    y = 315
    [[polygon.point]]
    x = 675
    y = 335
    [[polygon.point]]
    x = 675
    y = 245
    [[polygon.point]]
    x = 615
    y = 205
    [[polygon.point]]
    x = 550
    y = 205
    [[polygon.point]]
    x = 550
    y = 245
    [[polygon.point]]
    x = 465
    y = 315
    [[polygon.point]]
    x = 575
    y = 335

[[polygon]]
    [[polygon.point]]
    x =  590
    y =  167
    [[polygon.point]]
    x =  607
    y =  167
    [[polygon.point]]
    x =  607
    y =  117
    [[polygon.point]]
    x =  657
    y =  137
    [[polygon.point]]
    x =  657
    y =  47
    [[polygon.point]]
    x =  597
    y =  7
    [[polygon.point]]
    x =  532
    y =  7
    [[polygon.point]]
    x =  532
    y =  47
    [[polygon.point]]
    x =  447
    y =  117
    [[polygon.point]]
    x =  557
    y =  137